# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events on any branch.
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO to fetch libraries for Bluepill
      run: |
        cd ${{ github.workspace }}
        platformio lib -e esp32dev install

    # Runs a single command using the runners shell
    - uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        configurePreset: "Linux"
        buildPreset: "Linux"

    - name: Examine Output
      run: ls -al ${{ github.workspace }}/../RR32CanController-build-linux/test/sil

    # Actual testing happening
    - name: Run Unittest
      run: ${{ github.workspace }}/../RR32CanController-build-linux/test/sil/ApplicationSilTest
